[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[phases.start]
cmd = "bun run start"

[variables]
NIXPACKS_IGNORE_DETECTION = "true"

